In [2]:
import numpy as np


In [3]:
word1 = 'institutional'
word2 = 'invitations'

#adding the '#' to the word beginning
word1 = '#' + word1
word2 = '#' + word2

#making a matrix for the edit distance table, and a 2d list for backtrace
mat = np.zeros([len(word1),len(word2)])
backtrace = [[{'left': False, 'up': False , 'diag': False} for x in range(len(word2))] for y in range(len(word1))]

#setting the first row and column to 0123456...
mat[:,0] = list(range(len(word1)))
mat[0,:] = list(range(len(word2)))

#setting the backtrace for the first row and column in backtrace
#all beside [0,0] are set to up for the ones in the first column
#all beside [0,0] are set to left for the ones in the first row
#[0,0] stays at it's initial state of false false false
for direction in backtrace[1:][0]:
    direction['up'] = True
for direction in backtrace[0][1:]:
    direction['left'] = True

print(f'initial state of the edit distance tabel for <{word1[1:]}> and <{word2[1:]}>:', '\n')
print(mat)


initial state of the edit distance tabel for <institutional> and <invitations>: 

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 8.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 9.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [11.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [12.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [4]:
# 'i' is for rows and 'j is for columns'
for i in range(1, len(word1)):
    for j in range(1, len(word2)):
        #left and up always get a +1
        left = mat[i,j-1]+1
        up = mat[i-1,j]+1
        #diag doesnt get any + if the two characters are the same
        if word1[i] == word2[j]:
            diag = mat[i-1,j-1]
        #but it gets a +2 if the two characters are not the same
        else:
            diag = mat[i-1,j-1]+2
        #putting the min in the matrix and also evaluating which backtrace equated to the minimum
        the_min = min(left , up , diag)
        mat[i,j] = the_min
        backtrace[i][j] = {'left': left == the_min,
                            'up': up == the_min,
                            'diag': diag == the_min
                           }
print(mat)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9.  8.]
 [ 4.  3.  2.  3.  4.  3.  4.  5.  6.  7.  8.  9.]
 [ 5.  4.  3.  4.  3.  4.  5.  6.  5.  6.  7.  8.]
 [ 6.  5.  4.  5.  4.  3.  4.  5.  6.  7.  8.  9.]
 [ 7.  6.  5.  6.  5.  4.  5.  6.  7.  8.  9. 10.]
 [ 8.  7.  6.  7.  6.  5.  6.  5.  6.  7.  8.  9.]
 [ 9.  8.  7.  8.  7.  6.  7.  6.  5.  6.  7.  8.]
 [10.  9.  8.  9.  8.  7.  8.  7.  6.  5.  6.  7.]
 [11. 10.  9. 10.  9.  8.  9.  8.  7.  6.  5.  6.]
 [12. 11. 10. 11. 10.  9.  8.  9.  8.  7.  6.  7.]
 [13. 12. 11. 12. 11. 10.  9. 10.  9.  8.  7.  8.]]


In [5]:
#starting from the bottom right of the matrix
position = [len(word1)-1,len(word2)-1]
#for the output which is going to include * and stuff
word1p = []
word2p = []
#going to stop when we reach top left of the matrix the 0
while position != [0,0]:
    #we are going to prioritize diagonal movement (substitution) and then up (deletion)
    #but that's not necessary, we could have done it randomly
    if backtrace[position[0]][position[1]]['diag'] == True :
        #both get their own characters
        word1p.append(word1[position[0]])
        word2p.append(word2[position[1]])
        #diagonal moves in both axis
        position[0], position[1] = position[0]-1, position[1]-1
        continue
    if backtrace[position[0]][position[1]]['up'] == True :
        #up is a deletion so character from word1 transforms into a *
        word1p.append(word1[position[0]])
        word2p.append('*')
        position[0] = position[0]-1
        continue
    if backtrace[position[0]][position[1]]['left'] == True :
        #left is an insertion so an empty space from word1 aka '*' transforms into a character from target word
        word1p.append('*')
        word2p.append(word2[position[1]])
        position[1] = position[1]-1
        continue

#we started from the end of the words so they are backwards.
word1p.reverse()
word2p.reverse()
#the * behind the list unpacks the list so we get separate charaters not a list with []
#it's just for extra neatness
print(*word1p)
print(*'↓'*len(word1p), sep = ' ')
print(*word2p)
print(f'Edit Distance: {int(mat[len(word1)-1, len(word2)-1])}')

i n s t i t u t i o n a l
↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓
i n * v i t a t i o n * s
Edit Distance: 8
